# **Introduction à NumPy**
Ce notebook est une mini formation sur `NumPy`, illustrée avec des exemples pratiques.


## **1. Installation et importation**

In [1]:
%pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [2]:
import numpy as np

## **2. Création et manipulation des tableaux NumPy**

### **2.1 Création d'arrays**

In [3]:

# Création d'un tableau à partir d'une liste
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)

# Création d'un tableau multidimensionnel
arr2 = np.array([[1, 2, 3], [4, 5, 6]])
print(arr2)


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]


### **2.2 Création d'arrays spécifiques**

In [4]:

# Tableau de zéros
arr_zeros = np.zeros((3, 3))
print(arr_zeros)

# Tableau de uns
arr_ones = np.ones((2, 4))
print(arr_ones)

# Tableau d'une séquence de nombres
arr_range = np.arange(0, 10, 2)  # De 0 à 10 avec un pas de 2
print(arr_range)

# Tableau de valeurs équidistantes
arr_linspace = np.linspace(0, 1, 5)  # 5 valeurs entre 0 et 1
print(arr_linspace)

# Tableau aléatoire
arr_random = np.random.rand(3, 3)
print(arr_random)


[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]
[[0.96400074 0.54805251 0.86142384]
 [0.0055127  0.78695864 0.76147642]
 [0.75260953 0.81823296 0.72920731]]


## **3. Exploration et analyse des tableaux NumPy**

In [5]:

# Forme et dimensions
print("Shape:", arr2.shape)  # Nombre de lignes et colonnes
print("Taille:", arr2.size)  # Nombre total d'éléments
print("Type de données:", arr2.dtype)  # Type des éléments

# Indexation et slicing
print("Premier élément:", arr1[0])
print("Dernière ligne du tableau 2D:", arr2[-1])

# Extraction d'une sous-matrice
sub_matrix = arr2[:, 1:]  # Toutes les lignes, colonnes 1 et suivantes
print(sub_matrix)


Shape: (2, 3)
Taille: 6
Type de données: int64
Premier élément: 1
Dernière ligne du tableau 2D: [4 5 6]
[[2 3]
 [5 6]]


## **4. Opérations mathématiques avec NumPy**

In [7]:

# Opérations élémentaires
arr = np.array([10, 20, 30, 40])
print("Addition:", arr + 10)
print("Multiplication:", arr * 2)
print("Exponentielle:", np.exp(arr))
print("Racine carrée:", np.sqrt(arr))

# Opérations entre tableaux
arr_a = np.array([1, 2, 3])
arr_b = np.array([4, 5, 6])
print("Addition entre tableaux:", arr_a + arr_b)
print("Multiplication élément par élément:", arr_a * arr_b)

# Produit matriciel
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
prod = np.dot(mat1, mat2)
print("Produit matriciel:", prod)


Addition: [20 30 40 50]
Multiplication: [20 40 60 80]
Exponentielle: [2.20264658e+04 4.85165195e+08 1.06864746e+13 2.35385267e+17]
Racine carrée: [3.16227766 4.47213595 5.47722558 6.32455532]
Addition entre tableaux: [5 7 9]
Multiplication élément par élément: [ 4 10 18]
Produit matriciel: [[19 22]
 [43 50]]


## **5. Manipulation des tableaux**

In [8]:

# Changement de forme (reshape)
arr_reshaped = np.arange(1, 10).reshape(3, 3)
print("Tableau reshaped:" , arr_reshaped)

# Transposition
print("Transposé:", arr_reshaped.T)

# Concatenation
arr3 = np.array([[10, 20, 30]])
concat_verticale = np.vstack((arr_reshaped, arr3))
print("Concaténation verticale:", concat_verticale)

concat_horizontale = np.hstack((arr_reshaped, arr3.T))
print("Concaténation horizontale:", concat_horizontale)


Tableau reshaped: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Transposé: [[1 4 7]
 [2 5 8]
 [3 6 9]]
Concaténation verticale: [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 20 30]]
Concaténation horizontale: [[ 1  2  3 10]
 [ 4  5  6 20]
 [ 7  8  9 30]]


## **6. Statistiques avec NumPy**

In [9]:

arr_stats = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print("Moyenne:", np.mean(arr_stats))
print("Médiane:", np.median(arr_stats))
print("Somme:", np.sum(arr_stats))
print("Écart-type:", np.std(arr_stats))
print("Valeur max:", np.max(arr_stats))
print("Valeur min:", np.min(arr_stats))

# Statistiques sur un axe spécifique
print("Somme par colonnes:", np.sum(arr_stats, axis=0))
print("Somme par lignes:", np.sum(arr_stats, axis=1))


Moyenne: 5.0
Médiane: 5.0
Somme: 45
Écart-type: 2.581988897471611
Valeur max: 9
Valeur min: 1
Somme par colonnes: [12 15 18]
Somme par lignes: [ 6 15 24]


## **7. Gestion des valeurs manquantes et infinités**

In [10]:

arr_nan = np.array([1, 2, np.nan, 4, np.nan, 6])
print("Nombre de NaN:", np.isnan(arr_nan).sum())

# Remplacement des NaN
arr_nan[np.isnan(arr_nan)] = 0
print("Après remplacement des NaN:", arr_nan)

# Gestion des infinis
arr_inf = np.array([1, 2, np.inf, 4, -np.inf, 6])
arr_inf[arr_inf == np.inf] = 1000  # Remplacement des infinis
arr_inf[arr_inf == -np.inf] = -1000
print("Après gestion des infinis:", arr_inf)


Nombre de NaN: 2
Après remplacement des NaN: [1. 2. 0. 4. 0. 6.]
Après gestion des infinis: [    1.     2.  1000.     4. -1000.     6.]


## **8. Sauvegarde et chargement de données**

In [11]:

# Sauvegarde en format NumPy
np.save("data.npy", arr_stats)

# Chargement
arr_loaded = np.load("data.npy")
print("Données chargées:", arr_loaded)

# Sauvegarde en format texte
np.savetxt("data.txt", arr_stats, delimiter=",")
arr_loaded_txt = np.loadtxt("data.txt", delimiter=",")
print("Données chargées depuis fichier texte:", arr_loaded_txt)


Données chargées: [[1 2 3]
 [4 5 6]
 [7 8 9]]
Données chargées depuis fichier texte: [[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


`NumPy` est un outil essentiel pour manipuler des données numériques en Python.
Essayez de modifier les cellules pour tester d'autres transformations ! 🚀